# docker-compose.yml
version: '3.8'

services:
  api-gateway:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - microservices-net
    depends_on:
      - scraper-service

  scraper-service:
    build: 
      context: ./service-scraper
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://job-mongo:27017
    networks:
      - microservices-net
    depends_on:
      - job-mongo

  job-mongo:
    image: mongo:latest
    ports:
      - "27017:27017" # Exposed only for local debugging/compass
    volumes:
      - mongo_data:/data/db
    networks:
      - microservices-net

  user-postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: job_aggregator_users
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-net

  user-service:
    build:
      context: ./service-user
      dockerfile: Dockerfile
    environment:
      # Use the container name 'user-postgres' to connect internally
      - DATABASE_URL=postgresql://admin:password123@user-postgres:5432/job_aggregator_users?schema=public
      # Point the gRPC client to the Python container's internal network address
      - RESUME_GRPC_URL=resume-service:50051 
    ports:
      - "3000:3000" # Optional: only expose if you want to bypass Nginx for debugging
    networks:
      - microservices-net
    depends_on:
      - user-postgres
      - resume-service

  resume-service:
    build:
      context: ./service-resume
      dockerfile: Dockerfile
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge

volumes:
  mongo_data:
  postgres_data:
