# docker-compose.yml
version: '3.8'

services:
  api-gateway:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - microservices-net
    depends_on:
      - scraper-service

  scraper-service:
    build: 
      context: ./service-scraper
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://job-mongo:27017
    networks:
      - microservices-net
    depends_on:
      - job-mongo

  job-mongo:
    image: mongo:latest
    ports:
      - "27017:27017" # Exposed only for local debugging/compass
    volumes:
      - mongo_data:/data/db
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge

volumes:
  mongo_data:
