# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resume.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'resume.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cresume.proto\x12\x06resume\"!\n\x0cParseRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t\"0\n\rParseResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06skills\x18\x02 \x03(\t2J\n\x0cResumeParser\x12:\n\x0bParseResume\x12\x14.resume.ParseRequest\x1a\x15.resume.ParseResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'resume_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PARSEREQUEST']._serialized_start=24
  _globals['_PARSEREQUEST']._serialized_end=57
  _globals['_PARSERESPONSE']._serialized_start=59
  _globals['_PARSERESPONSE']._serialized_end=107
  _globals['_RESUMEPARSER']._serialized_start=109
  _globals['_RESUMEPARSER']._serialized_end=183
# @@protoc_insertion_point(module_scope)
